
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Neumaticos_del_Cibao.Database
{

using System;
    using System.Collections.Generic;
    
public partial class Client
{

    public long Id { get; set; }

    public string Name { get; set; }

    public Nullable<long> RNC { get; set; }

    public Nullable<long> NCF { get; set; }

    public string Credit { get; set; }

    public Nullable<long> CreditLimit { get; set; }

    public string Adress { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string ContactPhone { get; set; }

    public string ContactName { get; set; }

    public string ContactEmail { get; set; }

    public string ContactExt { get; set; }

    public string ContactCharge { get; set; }

}

}
