//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neumaticos_del_Cibao.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditSalesBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CreditSalesBill()
        {
            this.CreditSalesBillsRegisters = new HashSet<CreditSalesBillsRegister>();
        }
    
        public long SalesBillId { get; set; }
        public Nullable<double> Payed { get; set; }
        public Nullable<double> Owed { get; set; }
        public string DonePaying { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditSalesBillsRegister> CreditSalesBillsRegisters { get; set; }
        public virtual SalesBill SalesBill { get; set; }
    }
}
