//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neumaticos_del_Cibao.Database
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class Inventory
    {
        public long Id { get; set; }
        public Nullable<long> Article { get; set; }
        public Nullable<long> Quantity { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Article Article1 { get; set; }
    }
}
