
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Neumaticos_del_Cibao.Database
{

using System;
    using System.Collections.Generic;
    
public partial class Option
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Option()
    {

        this.Permissions = new HashSet<Permission>();

    }


    public long Id { get; set; }

    public string OptionTitle { get; set; }

    public string OptionType { get; set; }

    public string ClassView { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Permission> Permissions { get; set; }

}

}
