//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neumaticos_del_Cibao.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesBill()
        {
            this.SalesBillArticles = new HashSet<SalesBillArticle>();
        }
    
        public long Id { get; set; }
        public Nullable<long> ClientId { get; set; }
        public string BillCode { get; set; }
        public string Date { get; set; }
        public string ITBIS { get; set; }
        public Nullable<long> TotalArticles { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesBillArticle> SalesBillArticles { get; set; }
    }
}
