//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neumaticos_del_Cibao.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesBillArticle
    {
        public long Id { get; set; }
        public long ArticleId { get; set; }
        public long Quantity { get; set; }
        public long SalesBillId { get; set; }
        public double ArticlePrice { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual SalesBill SalesBill { get; set; }
    }
}
