
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Neumaticos_del_Cibao.Database
{

using System;
    using System.Collections.Generic;
    
public partial class ShoppingOption
{

    public long Id { get; set; }

    public string Title { get; set; }

    public string OptionTitle { get; set; }

    public string OptionType { get; set; }

    public string ClassView { get; set; }

}

}
