BEGIN TRANSACTION;
CREATE TABLE `Inventory` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Article`	INTEGER,
	`Quantity`	INTEGER DEFAULT 0,
	`Price`	REAL DEFAULT 0,
	FOREIGN KEY(`Article`) REFERENCES Articles(Id)
);
COMMIT;
